### ISSUE TITLE
(NPC) Infesting Jormungar

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#10]
Description: Infesting Jormungar Aggro working wrong

Current behaviour: When being aggro'ed they just look at you, and dont move towards you / attack

Expected behaviour: They should move towards you and fight

Steps to reproduce the problem: 

1. Aggro Infesting Jormungar
2. The NPC Wowhead: http://www.wowhead.com/npc=30148/infesting-jormungar
3. The NPC OpenWoW: http://wotlk.openwow.com/npc=30148

**Comment by DoctorCookie** [comment]
Maybe one time bug, Working properly now.
