### ISSUE TITLE
(Quest) Ignis the Furnace Master Must Die!

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#12]
Description: Ignis the Furnace Master Must Die available in the wrong season

Current behaviour: Ulduar season quest "Ignis the Furnace Master Must Die!" is available in Naxx season.

Expected behaviour: Quest should be possible only in Ulduar season

Steps to reproduce the problem:
 1. Accept Quest "Ignis the Furnace Master Must Die!"

Aggro Infesting Jormungar
The Quest Wowhead: http://www.wowhead.com/quest=24587/ignis-the-furnace-master-must-die
The Quest OpenWoW: http://wotlk.openwow.com/quest=24587

**Comment by DoctorCookie** [comment]
Confirm, will be fixed next update.

**Comment by DoctorCookie** [comment]
Fixed
