### ISSUE TITLE
[Raid] Eye of Etenity

### ISSUE THREAD

**Issue by Poli93** [DoctorCookie/WoWIL-Issues#14]
**Description:**
Power Sparks spawn during the encounter and empower Malygos once they reach him. He consumes the Spark which buffs his damage by 50%.

**Current behaviour:** (Tell us what happens.)
The Spark cannot be Death Gripped, when the Grip ability is being used on him, his aggro changes to you (taunt) and nothing else happens.

**Expected behaviour:** (Tell us what should happen instead.)
When Death Gripping he should come to the gripping DK.

**Steps to reproduce the problem:**
1. join a EOE raid
2. attempt to grip a Power Spark
3. get bummed

**Evidence to support my claim:**
http://wowwiki.wikia.com/wiki/Malygos_(tactics)
"Power Sparks: At regular intervals throughout the encounter, a portal will appear in the empty space away from the platform, between two of the pillars, and spawn a Power Spark. This Power Spark will slowly move towards Malygos and give him a temporary buff upon reaching him which increases all damage done by 50%, unless killed first. When players kill a Power Spark, it will leave a temporary patch of electricity on the ground which will buff players, increasing damage dealt by 50%. This buff will stack. During Vortex, Power Sparks stop moving; however, once you begin to fall from Vortex, they start moving again. Power Sparks can be Death Gripped, snared, rooted, stunned, incapacitated, and so on."

**Comment by DoctorCookie** [comment]
Fixed will up next update.
