### ISSUE TITLE
(NPC) Katherine Lee <Cooking Trainer>

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#15]
Description: Kathrine Lee should randomly give 1 random daily quest each day, out of 5 random options. She currently offers only 3 of the 5.

Current behaviour: Only 3/5 Quests currently are handed out (Tested 21 days in a row)

Expected behaviour: Should give 1 random quest each day out of 5 options

Steps to reproduce the problem:
1. Take random quest from Kathrine Lee
2. Repeat every day

The NPC Wowhead: http://www.wowhead.com/npc=28705/katherine-lee
The NPC OpenWoW: http://wotlk.openwow.com/npc=28705

**Comment by DoctorCookie** [comment]
Fixed
