### ISSUE TITLE
(NPC) Morcrush

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#16]
Description: Morcrush should be moving arround certain areas. He doesnt.

Current behaviour: Morcrush stays in 1 place 

Expected behaviour: Should move arround a few different zones

Steps to reproduce the problem:
1. Find Morcrush
2. Watch him not moving

The NPC Wowhead: http://www.wowhead.com/npc=18690/morcrush
The NPC OpenWoW: http://wotlk.openwow.com/npc=18690

**Comment by DoctorCookie** [comment]
Won't fix.
