### ISSUE TITLE
(NPC) Naka <Cooking Trainer & Supplies>

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#18]
Description: This NPC can be found in Zangarmarsh (Cenarion Refuge)

Current behaviour: Does not have any recipes or training options

Expected behaviour: Should have training for cooking and many recipes

Steps to reproduce the problem:
1. Find Naka
2. Try training / buying recipes

The NPC Wowhead: http://www.wowhead.com/npc=18993/naka
The NPC OpenWoW: http://wotlk.openwow.com/npc=18993

**Comment by DoctorCookie** [comment]
https://github.com/DoctorCookie/WoWIL-Issues/issues/19
