### ISSUE TITLE
Jack Trapper <Cooking Trainer>

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#19]
Description: This NPC can be found in Shattrath City.

Current behaviour: Does not have any recipes or training options

Expected behaviour: Should have training for cooking and many recipes

Steps to reproduce the problem:
1. Find Jack Trapper
2. Try training / buying recipes

The NPC Wowhead: http://www.wowhead.com/npc=19185/jack-trapper
The NPC OpenWoW: http://wotlk.openwow.com/npc=19185

**Comment by DoctorCookie** [comment]
Maybe you already learnt all his recipes, the link on wowhead is incorrect version of him.

**Comment by durrrr** [comment]
No, i didnt, and has no training as well.

**Comment by DoctorCookie** [comment]
https://postimg.org/image/5wddeh2nh/
