### ISSUE TITLE
The violet hold 

### ISSUE THREAD

**Issue by Nividan** [DoctorCookie/WoWIL-Issues#20]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Players don't get rep when running with tabard

**Expected behaviour:** 
When a player run the instance The violet hold with rep tabard he should get rep points for every mob he kill.
**Current behaviour:**
The player is not getting any rep points

**Comment by DoctorCookie** [comment]
That's not bug, it's intended.
