### ISSUE TITLE
Hunter's bugs- hunter's mark

### ISSUE THREAD

**Issue by Subjugation** [DoctorCookie/WoWIL-Issues#22]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Hunter's mark is an ability used by hunter's to increase their attack power on the target by a certain amount and also allow them to see the target in stealth should it stealth.

**Current behaviour:** (Tell us what happens.) Hunter's mark currently removes an already marked target from stealth when used.

**Expected behaviour:** (Tell us what should happen instead.) remark the target but does not remove stealth.

**Steps to reproduce the problem:**

1. open a hunter, duel a rogue or a feral.
2. Mark the target and have it stealth
3. remark the target and see how it makes it pop out of stealth

**Comment by DoctorCookie** [comment]
Source?

**Comment by DoctorCookie** [comment]
Closed, OP now answering.
