### ISSUE TITLE
Warlock | felhunter's offensive dispel magic

### ISSUE THREAD

**Issue by Subjugation** [DoctorCookie/WoWIL-Issues#23]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Devour magic is an ability that belongs to the felhunter, a warlock pet. The tooltip reads-
Purges 1 harmful magic effect from a friend or 1 beneficial magic effect from an enemy. if an effect is devoured, the felhunter will be healed for 1150.

**Current behaviour:** (Tell us what happens.) At the moment it is possible to dispel self and party members. However it impossible to use the felhunter's devour magic offensive capability.

**Expected behaviour:** (Tell us what should happen instead.)
The felhunter should dispel 1 beneficial magic buff from the target.

**Steps to reproduce the problem:**

1. open a warlock and summon a fel hunter
2. find a target with a magic buff
3. try to dispel it and see that it doesnt work.

**Comment by DoctorCookie** [comment]
https://github.com/DoctorCookie/WoWIL-Issues/issues/8
