### ISSUE TITLE
(NPC) Feralfen Hunter {Item Drop Chance Not Correct %}

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#24]
Description: This NPC can be found in Zangarmarsh.

Current behaviour: Drop chance of "Feralfen Protection Totem" should be 45%. Its no where near that.

Expected behaviour: Drop chance of "Feralfen Protection Totem" should be 45%.

Steps to reproduce the problem:
1. Find Feralfen Hunters
2. Kill to drop Feralfen Protection Totems
3. Drops less then 1/6 - 1/8

The NPC Wowhead: http://www.wowhead.com/npc=18113/feralfen-hunter
The NPC OpenWoW: http://wotlk.openwow.com/npc=18113

**Comment by DoctorCookie** [comment]
Fixed
