### ISSUE TITLE
(NPC) Marsh Lurker

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#26]
Description: This NPC can be found in Zangarmarsh.

Current behaviour: Able to target, but not attack in any way

Expected behaviour: Should be an attackable NPC

Steps to reproduce the problem:
1. Enter the cave between Zangramarsh and Terokkar Forest
2. Find NPC "Marsh Lurker" at the entrance of the cave
3. Try attacking him

The NPC Wowhead: http://www.wowhead.com/npc=18136/marsh-lurker
The NPC OpenWoW: http://wotlk.openwow.com/npc=18136

**Comment by DoctorCookie** [comment]
I can attack them.

**Comment by durrrr** [comment]
It is not all of them.
It is 1, in the entrance of the cave.
Should i start bringing screenshots ?

**Comment by DoctorCookie** [comment]
If out of the 15 Marsh Lurkers one of them is bugged, it's ok, you don't have to report in on github just tell a GM to kill it and he will respawn good as new since it's not a Script/Database problem.
