### ISSUE TITLE
(Quest) Lord Jaraxxus Must Die!

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#28]
Description: "Lord Jaraxxus Must Die!" available in the wrong season

Current behaviour: Ulduar season quest "Lord Jaraxxus Must Die!" is available in Naxx season

Expected behaviour: Quest should be possible only in Ulduar season

Steps to reproduce the problem:
1. Accept Quest "Lord Jaraxxus Must Die!"

The Quest Wowhead: http://www.wowhead.com/quest=24589/lord-jaraxxus-must-die
The Quest OpenWoW: http://wotlk.openwow.com/quest=24589

**Comment by DoctorCookie** [comment]
Fixed
