### ISSUE TITLE
(Quest) Sewer Stew

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#3]
Description: Sewer Stew is a quest where you should collect carrots from Crystalsong Forest and cook the carrots collected into a Sewer Stew and complete the quest.

Current behaviour: Carrots are currently missing from Crystalsong Forest where they should be located

Expected behaviour: Carrots should be spread arround the area of Crystalsong Forest

Steps to reproduce the problem:
1. Follow the questline of "Sewer Stew"
2. Go to Crystalsong Forest
3. Try finding the Carrots

The Quest Wowhead: http://www.wowhead.com/quest=13102/sewer-stew
The Quest OpenWoW: http://wotlk.openwow.com/quest=13114

**Comment by DoctorCookie** [comment]
Quest working properly.
