### ISSUE TITLE
Incorrect Buffs Stacks 

### ISSUE THREAD

**Issue by DoctorCookie** [DoctorCookie/WoWIL-Issues#32]
Description: Some of the buffs are stacking even tho they shouldn't.

Current behaviour: All those buff are stacking together:
Misery + Improved Faerie Fire
Improved Scorch + Improved Shadow Bolt
Savage Combat + Blood Frenzy

Expected behaviour: They shouldn't.

**Comment by Poli93** [comment]
Confirmed.

**Comment by DoctorCookie** [comment]
Savage Combat + Blood Frenzy - FIXED

**Comment by DoctorCookie** [comment]
Improved Scorch + Improved Shadow Bolt - FIXED

**Comment by DoctorCookie** [comment]
Fixed.
Closing - https://github.com/DoctorCookie/WoWIL-Issues/issues/32
