### ISSUE TITLE
[BUG] Thorim Dark Rune Champion

### ISSUE THREAD

**Issue by Nividan** [DoctorCookie/WoWIL-Issues#34]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
On thorim you got add "Dark Rune Champion" he sould get disarm
**Current behaviour:** (Tell us what happens.)
The npc immune to disarm.
**Expected behaviour:** (Tell us what should happen instead.)
The npc sould get the disarm.

**Comment by DoctorCookie** [comment]
fixed
