### ISSUE TITLE
[Ignis] Activate Construct

### ISSUE THREAD

**Issue by Poli93** [DoctorCookie/WoWIL-Issues#35]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
3.56M HP. For every second that a construct is in a Scorch area it gains a stacking speed buff. At 10 stacks it will turn Molten. When Molten it will gain extra haste and deal 2357 to 2643 Fire damage to enemies within 7 yards. Running the construct into water while Molten will turn it Brittle, stunning it, increasing its chance to be critically hit, and causing it to shatter if hit for more than 5000 damage in one attack.

**Current behaviour:** (Tell us what happens.)
Target turns into Molten when the stacks reach value of 20.

**Expected behaviour:** (Tell us what should happen instead.)
Target should turn into Molten when the stacks reach value of 10.

**Steps to reproduce the problem:**

1. Go to Ulduar
2. Fight Ignis
3. Move the adds into the Scorch

**Evidence to support my claim:**
Hotfix (2009-04-28): "The Ignis the Furnace Master encounter has received the following changes: The interrupt effect and duration of the damage from Flame Jets has been reduced, the damage from the Slag Pot has been reduced, the number of Heat stacks needed to transform an Iron Construct into a Molten state has been reduced, the base melee damage done by Ignis has been reduced, and the damage bonus Ignis receives from Strength of the Creator has been slightly increased. [5]" 

http://wowwiki.wikia.com/wiki/Ignis_the_Furnace_Master

**Comment by DoctorCookie** [comment]
Fixed, Require test in PTR.

**Comment by DoctorCookie** [comment]
Fixed, will up to the live version in a few days.
