### ISSUE TITLE
Emblema of conquest/triumph from Uld 25

### ISSUE THREAD

**Issue by Subjugation** [DoctorCookie/WoWIL-Issues#37]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.) bosses killed in uld 25 should yield an emblem of conquest. At the moment they either don't yield an emblem or alternatively yield an emblem of triumph (ToC- ilvl 245 gear)

**Expected behaviour:** (Tell us what should happen instead.) written above

**Steps to reproduce the problem:**
(Only personally tested in live game on flame levi and razorscale). Flame didn't yield emblems and razorscale yielded triumph badges
1. Go into uld
2. Kill bosses
3. See if they drop the (right), if any, emblem

**Comment by DoctorCookie** [comment]
Fixed, if a conquest drops in 10 raid, please report and don't abuse it.
