### ISSUE TITLE
[BUG] Yogg saron gurdian

### ISSUE THREAD

**Issue by Nividan** [DoctorCookie/WoWIL-Issues#38]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
In the first phase in yogg saron the guardians sould appear on a rate of 40 sec but they are appear after 10 sec+-  
**Current behaviour:** (Tell us what happens.)
The guardian appear with 10 sec diffrent from one to the other.
**Expected behaviour:** (Tell us what should happen instead.)
The gurdian appear with 40 sec difftent (If a player tuch the clode the time is reduce)

Wow wikki:
"Guardians also spawn automatically at an increasing rate, starting at about one per 40 seconds, increasing up to one per 10 seconds."
http://wowwiki.wikia.com/wiki/Yogg-Saron_(tactics)

**Comment by DoctorCookie** [comment]
They spawn if you walk over a cloud

**Comment by Nividan** [comment]
No thay are spawning by time, if you walk over cloud you spawn extra one and reduce the spawn timer (down from 40)

**Comment by DoctorCookie** [comment]
Yes, but did you checked it just by standing?

**Comment by Nividan** [comment]
I start the encounter and stand on the side

**Comment by DoctorCookie** [comment]
"Guardians also spawn automatically at an increasing rate, starting at about one per 40 seconds, increasing up to one per 10 seconds."
