### ISSUE TITLE
(Basic Movement) Releasing mount while in flight / moving does not continue momentum

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#4]
Description: When you release mount while flying towards a direction, you should continue going in that direction by the speed and momentum that you already had. What currently happens that you just drop in your place and lose all speed, causing you to fall directly down.

Current behaviour: ^

Expected behaviour: You should carry your momentum forward and continue with the same speed and direction you already had with your mount, and not drop straight down.

Steps to reproduce the problem: 

1. Get on any Mount / Fly Mount
2. Release it while moving in any location you want
3. Go straight down

**Comment by Raz240** [comment]
From my experience as a retail player, you should NOT retain your momentum. Do you have any proof supporting your claim?

**Comment by DoctorCookie** [comment]
Closed
