### ISSUE TITLE
(Warlock {Spell} ) Immolate - Conflagrate

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#41]
Description: Conflagrate should be able to be cast instantly after you put immolate on a target.
It is currently delayed by a few seconds

Current behaviour: Conflagrate should be able to be cast instantly after you put immolate on a target.
It is currently delayed by a few seconds

Expected behaviour: It should be instant there should be no delay

Steps to reproduce the problem:
1. Cast Immolate
2. Try to instantly cast Conflagrate after it
3. Delayed

The Spell (Conflagrate) Wowhead: http://www.wowhead.com/spell=156960/conflagrate
The Spell (Conflagrate) OpenWoW: http://wotlk.openwow.com/spell=17962
The Spell (Immolate) Wowhead: http://wotlk.openwow.com/spell=47811
The Spell (Immolate) OpenWoW: http://wotlk.openwow.com/spell=47811

**Comment by JudgeGM** [comment]
Not bugged
works fine 
checked already 10000000 times
