### ISSUE TITLE
(NPC) Blackwind Warp Chaser {Item Drop Chance Not Correct %}

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#47]
Description: This NPC can be found in Terokkar Forest

Current behaviour: Drop chance on "Warped Flesh" should be %50, It currently dropps 1/6-1/7

Expected behaviour:
Drop chance on "Warped Flesh" should be 50%

Steps to reproduce the problem:
1. Find the NPC
2. Kill a few to try and find "Warped Flesh"

The NPC Wowhead: http://www.wowhead.com/npc=23219/blackwind-warp-chaser
The NPC OpenWoW: http://wotlk.openwow.com/npc=23219

**Comment by DoctorCookie** [comment]
Changed to 50%.
