### ISSUE TITLE
(Item) Shadow Dust

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#49]
Description: This item can drop from a few NPCs in Terokkar Forest

Current behaviour: Drop chance is way too low on various NPCs in the area, Skettis Wing Guard, Skettis Windwalker, Skettis Soulcaller, Skettis Talonite and more...

Expected behaviour:
Drop chance on "Shadow Dust" should be:
http://i.imgur.com/3uGOP5k.jpg

Steps to reproduce the problem:
1. Find any of the NPCs that should drop "Shadow Dust"
2. Watch drop chance

The Item Wowhead: http://www.wowhead.com/item=32388/shadow-dust
The Item OpenWoW: http://wotlk.openwow.com/item=32388

**Comment by DoctorCookie** [comment]
Changed according to openwow.

**Comment by durrrr** [comment]
Even tho' it changed, it is not what the percents are in openwow.
It currently drops 1/4 1/5 and it should be 33%-35%.

**Comment by DoctorCookie** [comment]
I changed it to 33%-35%, but it will update only after restart which will happen today or tomorrow.
