### ISSUE TITLE
(Quest) Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#5]
Description: Stefan in Ebon Watch wants you to use Nass to collect 10 hair samples from Withered Trolls.

Current behaviour: Nass is not being summoned, and you cannot do the kicking part of the quest

Expected behaviour: Nass should be summoned and you should use him to kick the Trolls

Steps to reproduce the problem: Accept quest "Kickin' Nass and Takin' Manes", or try re-summoning Nass from the quest giver NPC, which also does not work

Go to Crystalsong Forest
1. Try finding the Carrots
2. The Quest Wowhead: http://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes
3. The Quest OpenWoW: http://wotlk.openwow.com/quest=13114

**Comment by BlackangelWow** [comment]
Both quests works fine - 07/11/2016 
Ill be here at evening ill show you
