### ISSUE TITLE
(Name) Unknown - Players Randomly appear as "Unknown"

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#56]
Description: Sometimes, happens a lot in raids or battlegrounds, people appear as name "Unknown", which disrupts the group and the battleground / raid / dungeon

Current behaviour: Players randomly appear as "Unknown" also causing raid / raid leader to not see them in the party / group

Expected behaviour:
Naming should not change to "Unknown" at any time

Steps to reproduce the problem:
1. Watch people names randomly
2. Watch them becoming Unknown or getting out of the group because of it

**Comment by DoctorCookie** [comment]
That's client bug, probably due to data lose in the loading, /reload will fix it.

**Comment by durrrr** [comment]
It continues to happen to many people.
Sometimes relog or game restart fixes it, but sometimes doesnt.
But it does happen to many people at many different times and should be handled somehow.

**Comment by durrrr** [comment]
Still happens constantly.
Example from today:
http://i.imgur.com/BAujcUC.jpg
