### ISSUE TITLE
(Spell) Horn of Winter / (Spell) Strength of Earth Totem - Stack

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#57]
Description: "Horn of Winter" (Death Knight) / "Strength of Earth Totem" (Shaman) buffs stack

Current behaviour: The buffs above stack, even tho' they should not

Expected behaviour:
"Horn of Winter" and "Strength of Earth Totem" should not stack

Steps to reproduce the problem:
1. Use spell "Horn of Winter" while in group
2. Use spell "Strength of Earth Totem" while in group

The Spell Wowhead: http://www.wowhead.com/spell=57330/horn-of-winter
The 2nd Spell Wowhead: http://www.wowhead.com/spell=31633/strength-of-earth-totem
The Spell OpenWow: http://wotlk.openwow.com/spell=57623
The 2nd Spell OpenWow: http://wotlk.openwow.com/spell=65991

**Comment by DoctorCookie** [comment]
Visual bug, look at the stats and you will see they are not really stacking.

**Comment by durrrr** [comment]
Even a visual bug, would count as a bug.
