### ISSUE TITLE
(Spell) Blessing of Kings / (Spell) Greater Blessing of Kings - Stack

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#58]
Description: "Blessing of Kings / "Greater Blessing of Kings" stack

Current behaviour: The buffs above stack, even tho' they should not

Expected behaviour:
"Blessing of Kings" and "Greater Blessing of Kings" should not stack

Steps to reproduce the problem:

1. Use spell "Blessing of Kings" while in group
2. Use spell "Greater Blessing of Kings" while in group

The Spell Wowhead: http://www.wowhead.com/spell=165713/blessing-of-kings
The 2nd Spell Wowhead: http://www.wowhead.com/spell=203538/greater-blessing-of-kings
The Spell OpenWow: http://wotlk.openwow.com/spell=43223
The 2nd Spell OpenWow: http://wotlk.openwow.com/spell=20217

**Comment by DoctorCookie** [comment]
Just visual bug.

**Comment by durrrr** [comment]
Visual bug is a bug ;)

**Comment by DoctorCookie** [comment]
Sorry, I forgot to mention, we can't fix visual bugs atm since we need to edit MPQ files for that, Maybe in the future when we will have our own lancher while is unlikely.
Thanks for the report anyway.
