### ISSUE TITLE
(Item) Glyph of Stoneclaw Totem

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#59]
Description: Use: Your Stoneclaw Totem also places a damage absorb shield on you, equal to 4 times the strength of the shield it places on your totems.

Current behaviour: Nothing happens after using the glyph, not the shield effect, or damage absorb

Expected behaviour:
"Your Stoneclaw Totem also places a damage absorb shield on you, equal to 4 times the strength of the shield it places on your totems."

Steps to reproduce the problem:
1. Use Glyph of "Stoneclaw Totem"
2. Use spell "Stoneclaw Totem"

The Glyph Openwow: http://wotlk.openwow.com/item=45778

**Comment by DoctorCookie** [comment]
That's working just fine, no idea how you checked that.
Please consider reading how to use the glyph before reporting it as bug.
Thanks :).
