### ISSUE TITLE
(NPC) Kylene

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#60]
Description: This NPC can be found in Shattrath City

Current behaviour: Has no recipes to teach

Expected behaviour:
The NPC should be teaching atleast 3 recipes according to Openwow and many more according to Wowhead

Steps to reproduce the problem:
1. Find "Kylene"
2. Try learn new Cooking recipes from her

The NPC Wowhead: http://www.wowhead.com/npc=19186/kylene
The NPC OpenWoW: http://wotlk.openwow.com/npc=19186

**Comment by DoctorCookie** [comment]
yes, he does.
![wowscrnshot_122016_132218](https://cloud.githubusercontent.com/assets/18441944/21348799/6f5259b0-c6b7-11e6-968f-2e72de554672.jpg)

please check before reporting bugs.

**Comment by durrrr** [comment]
It seems like for some people it does and for some people it doesnt.
Because i checked it myself, with a leveling character, and it didnt have any.
And its not the only one, other npcs of cooking from outland as well.
