### ISSUE TITLE
(NPC) Doras <Wind Rider Master>

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#62]
Description: This NPC can be found in Orgrimmar

Current behaviour: Sometimes when attacked, or just randomly without being attacked, starts running arround wildly and not returning to its place, which does not allow people to fly out of orgrimmar the main city of the horde
(It was reported a few times in different time-lines in the last few days)

Expected behaviour:
It should be the flightmaster of Orgrimmar, it should return to its place, even after attacked, and act normal and not run arround without a reason

Steps to reproduce the problem:
1. Find "Doras" going crazy
2. Try flying while she goes wild

The NPC Wowhead: http://www.wowhead.com/npc=31426/doras
The NPC OpenWoW: http://wotlk.openwow.com/npc=31426

**Comment by DoctorCookie** [comment]
fixed
