### ISSUE TITLE
(Object) Wild Mustard

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#67]
Description: This object can be found in Dalaran while doing quest "Mustard Dogs!".

Current behaviour: 
The first one is glowing, but not visible or clickable, seems underground
http://i.imgur.com/TxCojb2.jpg

Expected behaviour:
It should be glowing, visible and clickable 

Steps to reproduce the problem:
1. Find the first object near the entrance to dalaran sewers
2. Try to click it, or find the object glowing at all

The Object Wowhead: http://www.wowhead.com/object=192827/wild-mustard
The Object OpenWoW: http://wotlk.openwow.com/object=192827
The Quest Wowhead: http://www.wowhead.com/quest=13116/mustard-dogs
The Quest OpenWoW: http://wotlk.openwow.com/quest=13116

**Comment by DoctorCookie** [comment]
fixed
