### ISSUE TITLE
(Item) Glyph of Dash

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#69]
Description: Glyph of Dash: Druid Glyph
Use: Reduces the cooldown of your Dash ability by 20%.

Current behaviour: Does not do nothing to cooldown

Expected behaviour:
"Use: Reduces the cooldown of your Dash ability by 20%."

Steps to reproduce the problem:
1. Use "Glyph of Dash"
2. Use spell "Dash" after applying the glyph

The Glyph Openwow: http://wotlk.openwow.com/item=43674
The Spell Openwow: http://wotlk.openwow.com/spell=33357

**Comment by DoctorCookie** [comment]
before:
![wowscrnshot_122016_131633](https://cloud.githubusercontent.com/assets/18441944/21348733/27db0118-c6b7-11e6-9f62-e98471876399.jpg)
after:
![wowscrnshot_122016_132020](https://cloud.githubusercontent.com/assets/18441944/21348735/2a303064-c6b7-11e6-96ba-d78c73718cdd.jpg)

Checked with stopwatch and the cooldown is exactly 2.4m.

**Comment by durrrr** [comment]
Checked with 2 druids, i dont know why your checks are different then mine and players.
Also checked with 2 different druids.
