### ISSUE TITLE
[Spell] Army of the Dead

### ISSUE THREAD

**Issue by Poli93** [DoctorCookie/WoWIL-Issues#7]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Army of the Dead currently does more damage than it should, during patch 3.3.0 on live AotD's cooldown was reduced to 10 minutes from 20, and the Ghoul's damage was reduced by 50%.

**Current behaviour:** (Tell us what happens.)
AotD does more damage than it should at the moment, they melee for around 300-500 and can crit up to 600+

**Expected behaviour:** (Tell us what should happen instead.)
The Ghouls should be able to crit obviously, but the base damage of their attacks should be around 150-200 and crits up to 300+. Exactly 50% reduction is what we're missing.

**Steps to reproduce the problem:**
1.  Make yourself a Death Knight, duh.
2.  Cast AotD next to any training dummy and see the damage.
3. There's no step 3 here really ;)

**Proof to support my claim:**
http://wow.gamepedia.com/Army_of_the_Dead
"WotLK Patch 3.3.0 (2009-12-08): The cooldown on this ability has been reduced from 20 minutes to 10 minutes. Army Ghoul damage dropped by 50%. Cannot be used in Arenas."

**Comment by DoctorCookie** [comment]
Confirm.

**Comment by DoctorCookie** [comment]
Fixed - 50% reduce dmg.
