### ISSUE TITLE
(Item) Kaliri Stew

### ISSUE THREAD

**Issue by durrrr** [DoctorCookie/WoWIL-Issues#70]
Description: 
Kaliri Stew
Item Level 1
Quest Item.

Current behaviour: When preparing "Kaliri Stew" there is no spell loading bar.

Expected behaviour:
"Kaliri Stew" while making should have a cast bar and you should know when the spell is going to finish or prepare. This causes players sometimes to leave in the middle of doing the spell, causing them to think it is completely bugged. If you just stay until the spell ends, even tho' there is no preperation or cast time letting you know when is it going to end.

Steps to reproduce the problem:
1. Find mats for "Kaliri Stew"
2. Open Cooking Fire
3. Prepare "Kaliri Stew"

The Item Wowhead: http://www.wowhead.com/item=33839/kaliri-stew
The Item Openwow: http://wotlk.openwow.com/item=33839

**Comment by DoctorCookie** [comment]
that's me cooking Karliri Stew.
![wowscrnshot_122016_131403](https://cloud.githubusercontent.com/assets/18441944/21348567/5d42113a-c6b6-11e6-9394-a873e7448205.jpg)

**Comment by durrrr** [comment]
Maybe its a clash of addons / script.
I checked it for 6-7 times now, and i dont see a casting bar like yours clearly shows.
Your seems working fine.
i'll picture next time.
