### ISSUE TITLE
[Warlock] FelHunter - Devour Magic [Enemy Target] - DUELS ONLY

### ISSUE THREAD

**Issue by JudgeGM** [DoctorCookie/WoWIL-Issues#8]
The spell Devour Magic of the Felhunter should purges 1 beneficial magic effect from an enemy. 

**Current behaviour:** (Tell us what happens.)
Nothing happen when you try to purge enemy

**Expected behaviour:** (Tell us what should happen instead.)
it should remove 1 beneficial Magic effect from an enemey

**Steps to reproduce the problem:**

1. Open warlock - Any build
2.Do Duel/BGs/Arena - ask someone to cast a beneficial spell on himself
3. try to devour it with fel hunter (Remove auto use)

**Comment by DoctorCookie** [comment]
Fixed - Will up next update.

**Comment by DoctorCookie** [comment]
Fixed in Bg's and Arenas but problem still occur in duels.
